version: 2
updates:
  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "daily"
    # Group patch and minor updates into a single PR.
    groups:
      minor_and_patches:
        update-types:
        - "minor"
        - "patch"
